[package]
name = "pcd8544"
version = "0.1.0"
authors = ["Michael Watzko <michael@watzko.de>"]
repository = "https://git.tallbyte.com/rust/pcd8544.git"
description = "Implementation to communicate and write to PCD8544 using embedded_hal as abstraction layer. WIP"
keywords = ["embedded", "display", "lcd", "pcd8544", "microcontroller"]
categories = ["embedded", "hardware-support", "no-std"]
license = "MIT"

[lib]

[dependencies.embedded-hal]
features = ["unproven"]
version = "0.1.0"